services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`delixia-server.triformine.dev`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"
      - "traefik.http.services.server.loadbalancer.server.port=2567"
    networks:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2567/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web:
    external: true